### ISSUE TITLE
Modularize and split write_main_dataset()

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/pyNSID#15]
Extract code from ``hdf_utils.model.write_main_dataset()`` and populate smaller helper functions listed below in ``hdf_utils.simple`` thereby making ``write_main_dataset()`` smaller and simpler to understand. Note, that ``write_main_dataset()`` may not already have code for all of these functions. 

Functions in ``hdf_utils.simple`` that need to be populated from :
* ``link_as_main()``
* ``check_and_link_ancillary()``
* ``validate_dims_against_main()``
* ``validate_main_dset()``
* ``validate_anc_h5_dsets()`` - <- convert to singular ancillary dataset?

**Comment by gduscher** [comment]
Rewrote:
validate_dims_against_main()
validate_main_dset()
