### ISSUE TITLE
Replace 'is_position' with 'dimension_type'

### ISSUE THREAD

**Issue by gduscher** [pycroscopy/pyNSID#18]
I think the boolean attribute of dimension "is_position" should be replaced by a more descriptive one by making it a variable ``dimension_type`` which could be 'position', 'spectral', 'time' or 'frame'.

This would make it easier to plot the data. 
For example:
two position in dimension_types and a spectral dimension must be a spectrum image versus one with a time dimension which makes it an image stack.
Three positions make it a volumetric dimension. 
One could add a 'reciprocal' dimension_type  for 4D STEM imaging.

I got this idea while working on 'NSIDDataset' which has a visualization part.

**Comment by ssomnath** [comment]
@gduscher - You are right. I think this is a better idea. What are the different types we need to have. ``time`` and ``spectral`` don't vary all that much in behavior though. How about ``real`` and ``reciprocal`` or something like that? Would this be sufficient? We can keep position and spectral as is in that case. Would that capture all possible variants of quantities?

**Comment by ssomnath** [comment]
@gduscher - as long as you feel that ``dimension_type`` provides sufficient information to translate NSID data to USID, we should be OK.
