### ISSUE TITLE
Fleshing out and cleaning example notebooks

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/pyNSID#29]
We need to add more narrative, comments etc to the example notebooks in the [notebooks folder](https://github.com/pycroscopy/pyNSID/tree/master/notebooks).

Also, consolidate examples ore delete redundant ones where appropriate.

These notebooks will become the sphinx gallery soon.

**Comment by ssomnath** [comment]
We need examples for:
1. Writing ``sidpy.Dataset`` object to NSID formatted HDF5 files - ``pyNSID.hdf_io. write_nsid_dataset``
2. Reading ``sidpy.Dataset`` object(s) from NSID formatted HDF5 files using ``pyNSID.NSIDReader``
3. Writing results from some analysis using ``pyNSID.hdf_io. write_results``

**Comment by ziatdinovmax** [comment]
> We need examples for:
> 
> 1. Writing `sidpy.Dataset` object to NSID formatted HDF5 files - `pyNSID.hdf_io. write_nsid_dataset`
> 2. Reading `sidpy.Dataset` object(s) from NSID formatted HDF5 files using `pyNSID.NSIDReader`
> 3. Writing results from some analysis using `pyNSID.hdf_io. write_results`

I'm not quite sure about item (3) - does it refer to sidpy.Dataset specifically?
Here's a draft for items 1 and 2: https://gist.github.com/ziatdinovmax/65d626350b9bb2a57e912c24b0e481e2

**Comment by ssomnath** [comment]
@ziatdinovmax - Sorry for the late reply. This slipped through the cracks. 

So (3) would be very similar to (1). In both cases we would be writing ``sidpy.Dataset`` objects to HDF5 in the ``NSID`` format. I guess the idea was to show users that we also have a function to write results as well to disk. It has been a while, I need to remind myself how ``write_nsid_dataset`` is different from ``write_results``.

The notebook you have looks pretty good! Please submit as PR and make sure older / duplicate examples from Gerd / others are removed to avoid confusion.

**Comment by ziatdinovmax** [comment]
@ssomnath No worries. I created a PR with the example notebook and also the updates to ```io.hdf_io``` utilities to reflect the recent changes in sidpy Dataset class (```.axes``` -> ```._axes```, ```.attrs``` -> ```.metadata```, and change the order of value and name when initializing Dimension).

**Comment by ssomnath** [comment]
@ziatdinovmax awesome! Looks like we can close this issue.
