### ISSUE TITLE
'Dataset' object has no attribute 'axes'

### ISSUE THREAD

**Issue by ziatdinovmax** [pycroscopy/pyNSID#33]
The error happens when trying to write a sidpy dataset to h5 file using ```nsid.hdf_io.write_nsid_dataset```. Used to work last week. Is this attribute gone forever?

Steps to reproduce:
1. Create a dummy sidpy dataset:
```dataset = sid.Dataset.from_array(np.random.random([4, 5, 10]), name='new')```
2. Try writing it to nsid-formatted h5 file:
```nsid.hdf_io.write_nsid_dataset(dataset, hf['Measurement_000/Channel_001'], main_data_name="new")```

**Comment by ssomnath** [comment]
Closing this since @ziatdinovmax addressed this in #34
