### ISSUE TITLE
NSID HDF5 reader and writer plugins for Hyperspy

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/pyNSID#41]
I wrote a [USID HDF5 reader + writer plugin](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/io_plugins/usid_hdf5.py) for HyperSpy a while back. Once NSID is stable, we should also write an NSID plugin.

**Comment by ssomnath** [comment]
We decided that it makes more sense to have a memory layer converter rather than in the file system. So this is no longer a pyNSID issue, but rather a SciFiReaders issue

**Comment by gduscher** [comment]
Isn’t it now a sidpy issue, since I added it to sidpy?

**Comment by ssomnath** [comment]
All data ingest should be contained within SciFiReaders rather than sidpy. sidpy is meant to have purely engineering and non-scientific tools.

**Comment by ssomnath** [comment]
@gduscher  - this issue has been moved to [here](https://github.com/pycroscopy/SciFiReaders/issues/29)
