### ISSUE TITLE
Commit changes for Dimension class from wite_main_dataset notebook into write_utils

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/pyNSID#5]

**Comment by gduscher** [comment]
write_main_dataset first version is out.
Enough to test datasets.
I don't know, how I an access the pyNSID version, also of now the  write_main_dataset  returns a h5_dataset and not a NSIDataset, because shape is not working there.

**Comment by ssomnath** [comment]
Both of these are fine:
1. We don't have the ``NSIDataset`` class completed
2. We would generally have a __version__ file with this pyNSID version. Again, we don't have this.
