### ISSUE TITLE
Regions of interest using  region references

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/pyNSID#8]
Note that ROIs can be multi-dimensional hypercubes - not just 2D areas

Recommended approach:
1. First solve [this](https://github.com/pycroscopy/pyUSID/issues/45) issue in pyUSID
2. Then gather existing functions for region_references from pyUSID
3. Develop a set of functions to write and read regions of interest using region references.

**Comment by ssomnath** [comment]
region reference usage and functionality has been carefully removed from pycroscopy and pyUSID.hdf_utils. All region references-specific functionality now live in ``pyUSID.io.reg_ref.py``.

A copy of these functions should stay in the current location in pyUSID for legacy / backward compatibility but these functions can be ported over and modified to suit NSID needs now

**Comment by ramav87** [comment]
Existing functions for region references in h5py is insufficient as it only allows for slice objects and not non-standard indexing (like lists of points). Therefore, an alternate route has been suggested which involves adding a region reference attribute to the NSIDataset, that could be setup as follows:

```
nsid_dataset.create_region() #dict('0':[0,5,3], '1':[2,10,15], 'capacitors') #pass a dictionary with the slice values and the name of the region, this should get stored
nsid.capacitors.points #gives back the dictionary used to make the region reference
nsid.capacitors.data #gives back the data
```

This is a TODO item, but it is low priority.

**Comment by ssomnath** [comment]
Moved to [sidpy](https://github.com/pycroscopy/sidpy/issues/27). Closing here
