### ISSUE TITLE
NSIDataset on Dask array

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/pyNSID#9]
NSIDataset can either be a virtual object or something that gets its content / meaning from HDF5 datasets similar to ``pyUSID.USIDataset``. Given that this class will extend ``dask.array`` (instead of ``numpy.ndarray`` for scalability), it will inherit all the mathematical and numerical analysis capabilities scientists actually want from a "measurement" object. Operations on this object such as ``sum``, ``mean``, etc. should result in NSIDataset objects instead of dask arrays. 

If and when the user is interested in writing such an object to HDF5, they can call ``object.to_hdf5()``, which basically calls ``hdf_utils.model.write_main_data()``. Since this class does not force users to ingest data from HDF5 datasets and because it inherits popular numerical analysis capabilities, this object will lower the barrier for people to start using NSIDataset. 

Do we want to support multi-step creation / construction of objects? Perhaps such a class could be written once the USIDataset counterpart (very easy) is written first. Then add the virtual-only aspect?

**Comment by ssomnath** [comment]
Develop NSIDataset(dask.core.array):

    1. Init function that figures out whether or not the provided object is a main dataset, if it is - finds and populates information from ancillary datasets
    2. Function for quickly getting different details about a reference axis - e.g. the name, units, quantity, unit values etc.
    3. Figure out how to make dimensions as first class attributes of the object as in obj.bias instead of obj.dimensions[‘bias’]
    4. Develop the visualize function - basically take guidance from USIDataset

**Comment by gduscher** [comment]
Write_main_dataset is working but the output is a h5_dataset. I could not get shape to work with the NSID dataset.

**Comment by ssomnath** [comment]
We want to ensure that NSIDataset extends `dask.core.array` instead of `h5py.Dataset` but accepts various kinds of inputs:
1. `h5py.Dataset` to start with - we already have this 
2. something in memory only / not in HDF5 file - a set of dask / numpy arrays + strings exactly like the `write_main_dataset`. Does it make sense that `write_main_dataset` does not exist by itself. Instead, `write_main_dataset` constructs a `NSIDataset` object and this object can be written to HDF5 using `NSIDataset.to_hdf5()` The reason I suggest this is to lower the barrier to users using (and enhancing) this class. 

@ramav87 mentioned that `write_main_dataset` expects too many parameters right now. Does it make sense to minimize the number of expected parameters? We just assign dummy values (not recommended by any means) for most of the metadata (quantity, units, etc.)

**Comment by ssomnath** [comment]
Requirements to create an NSIDataset has been lowered to just the N-dimensional array and a list of Dimension objects (if the object is being created in memory).
Requirements for Dimension have been lowered to the name and type (spectral / position ....). The values will conform to whatever is the size of the dimension on the N-dimensional dataset

**Comment by ramav87** [comment]
It is possible to have dynamic attributes for classes, see https://chase-seibert.github.io/blog/2013/04/12/getattr-setattr.html for details. Essentially use the  setattr(self, field, value) method

**Comment by gduscher** [comment]
The question is: should the NSIDataset then live completely in memory and store the data as USIDataset.
The hdf5 dimensions would no longer be needed, if we change to a dynamic class with data in dask arrays.

**Comment by ssomnath** [comment]
We will need some sort of a validation function when a user wants to manipulate the properties of the NSIDataset object like the name of a dimension (should not have two dimensions of the same name, dimension size should match the size of the core dataset). Life would be a lot easier if users could NOT directly manipulate certain properties of the Dimension objects. They would need to go through a "set" function that will allow us to validate whether the provided input is sensible. Or we can let them make mistakes and then we won't be able to write to disk.

**Comment by ssomnath** [comment]
Development has moved to ``sidpy.Dataset``. Closing issue here.
